services:
  frontend:
    build:
      context: serving
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST="service.local"
      - NGINX_PORT="8080"
    volumes:
      - ./frontend/dist:/var/www
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: app.Dockerfile

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: devpass

